name: easy_localization_generator
description: Generates the localization keys from an online Google Sheet or a local csv file.
version: 0.3.5
# author: Rin Luu Van <rinlv.hn@gmail.com>
homepage: https://github.com/rinlv/easy_localization_generator
issue_tracker: https://github.com/rinlv/easy_localization_generator/issues

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.2
  build_config: ^1.2.0
  source_gen: ^4.1.1
  http: ^1.6.0
  path: ^1.9.1
  csv: ^6.0.0
  intl: ^0.20.2
  analyzer: ^8.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter